// <auto-generated />
using System;
using System.Collections.Generic;
using CryptexAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptexAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251112035847_Added_TransactionHistory")]
    partial class Added_TransactionHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptexAPI.Models.FuethersDeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<int>("CoinId")
                        .HasColumnType("integer");

                    b.Property<double>("EnterPrice")
                        .HasColumnType("double precision");

                    b.Property<int>("Leverage")
                        .HasColumnType("integer");

                    b.Property<double>("MarginValue")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double>("StopLoss")
                        .HasColumnType("double precision");

                    b.Property<double>("TakeProfit")
                        .HasColumnType("double precision");

                    b.Property<int>("TypeOfDeal")
                        .HasColumnType("integer");

                    b.Property<int>("TypeOfMargin")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FuethersDeals");
                });

            modelBuilder.Entity("CryptexAPI.Models.Persons.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<double?>("Balance")
                        .HasColumnType("double precision");

                    b.Property<double?>("BalanceForCopyTrading")
                        .HasColumnType("double precision");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<int>>("FollowersIds")
                        .HasColumnType("integer[]");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("GoogleID")
                        .HasColumnType("text");

                    b.Property<double?>("Income")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSilent")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CryptexAPI.Models.TransactionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CoinAmount")
                        .HasColumnType("double precision");

                    b.Property<int?>("CoinName")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<double>("PricePerCoin")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<double>("UsdValueChange")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TransactionHistories");
                });

            modelBuilder.Entity("CryptexAPI.Models.Wallets.Coin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<int>("Name")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int?>("WalletForMarketId")
                        .HasColumnType("integer");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WalletForMarketId");

                    b.HasIndex("WalletId");

                    b.ToTable("Coins");
                });

            modelBuilder.Entity("CryptexAPI.Models.Wallets.SeedPhrase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<List<string>>("SeedPhraseValues")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("SeedPhrases");
                });

            modelBuilder.Entity("CryptexAPI.Models.Wallets.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SeedPhraseId")
                        .HasColumnType("integer");

                    b.Property<int>("WalletType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeedPhraseId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("CryptexAPI.Models.Wallets.WalletForMarket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SeedPhraseId")
                        .HasColumnType("integer");

                    b.Property<int>("WalletType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeedPhraseId");

                    b.ToTable("WalletForMarkets");
                });

            modelBuilder.Entity("CryptexAPI.Models.Persons.User", b =>
                {
                    b.HasOne("CryptexAPI.Models.Wallets.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptexAPI.Models.TransactionHistory", b =>
                {
                    b.HasOne("CryptexAPI.Models.Persons.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CryptexAPI.Models.Wallets.Coin", b =>
                {
                    b.HasOne("CryptexAPI.Models.Wallets.WalletForMarket", null)
                        .WithMany("AmountOfCoins")
                        .HasForeignKey("WalletForMarketId");

                    b.HasOne("CryptexAPI.Models.Wallets.Wallet", null)
                        .WithMany("AmountOfCoins")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptexAPI.Models.Wallets.Wallet", b =>
                {
                    b.HasOne("CryptexAPI.Models.Wallets.SeedPhrase", "SeedPhrase")
                        .WithMany()
                        .HasForeignKey("SeedPhraseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeedPhrase");
                });

            modelBuilder.Entity("CryptexAPI.Models.Wallets.WalletForMarket", b =>
                {
                    b.HasOne("CryptexAPI.Models.Wallets.SeedPhrase", "SeedPhrase")
                        .WithMany()
                        .HasForeignKey("SeedPhraseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeedPhrase");
                });

            modelBuilder.Entity("CryptexAPI.Models.Wallets.Wallet", b =>
                {
                    b.Navigation("AmountOfCoins");
                });

            modelBuilder.Entity("CryptexAPI.Models.Wallets.WalletForMarket", b =>
                {
                    b.Navigation("AmountOfCoins");
                });
#pragma warning restore 612, 618
        }
    }
}
